### ISSUE TITLE
some grass sprites incorrect size

### ISSUE THREAD

**Issue by zsilencer** [OpenRCT2/OpenGraphics#2]
The grass sprites are very good, but there is one small issue where two of them are one row of pixels too small when rendered.  Sprites #3 and sprite #11 are missing the bottom row of pixels when compared to the original graphics, this causes a small gap in rendering the terrain.

![nirvana gardens v4 2016-11-25 11-33-51](https://cloud.githubusercontent.com/assets/5456638/20633396/4e698cd6-b303-11e6-955d-717ba132865f.png)

**Comment by oli414** [comment]
Closing as we'll be redoing this sprite.
