### ISSUE TITLE
Tools and workflow?

### ISSUE THREAD

**Issue by mdtrooper** [OpenRCT2/OpenGraphics#22]
I want to help but I don't know how start.

- Is there a tool or parameter in cli mode of OpenTTD to extract the sprites?
- Is there a tool to pack the "custom sprites" into .dat file?

Thanks.

**Comment by duncanspumpkin** [comment]
Assume you mean OpenRCT2. We have a tool that can extract all sprites from dat files or g1.dat. 

https://github.com/OpenRCT2/OpenRCT2/wiki/Sprite-compiler

You shouldn't be creating .dat files but instead .parkobj files which are just zip files with the extension changed. Inside the zip you put all your images and your object.json file that has all the meta data. I suggest joining the discord for further info.

**Comment by oli414** [comment]
The best way to help currently is to just create objects using Blender without worrying to much about the rest of the process yet :-)
