### ISSUE TITLE
Multiple resolutions and animation frame count

### ISSUE THREAD

**Issue by CoderBaron** [OpenRCT2/OpenGraphics#23]
I think it would be a good idea to render the sprites in multiple resolutions as well as at least 24 frames per second for animations. 

This would allow future versions of OpenRCT2 to zoom in more into your park as well as give it a more fresh appearance for newer players. By storing the sprites in different sprite sheets, the sprite resolution could be choosen by the player in the game. 

Animations should always be rendered with a high frame count to allow for highly fluent animations. It would be easy in code to just skip X frames to simulate the original low-frame animations. 

Another game that has added such a feature is the Knights & Merchants Remake. 
Of course the default should always be the same resolution and frame count as RCT2 but I think this would make a nice addition to the game.

**Comment by duncanspumpkin** [comment]
We already handle multiple zoom images. All replacement objects need to work identical to existing objects for now otherwise there would be desync issues in multiplayer.

**Comment by oli414** [comment]
We will leave the possibility open to render at higher resolutions and framerates in the future but we will not make it our first priority. Initially, we just want to focus on getting graphics done that match with what was originally there in terms of resolutions, bit depth, and framerate.
