### ISSUE TITLE
Pos.txt calculations unable to output positive values

### ISSUE THREAD

**Issue by zrowny** [OpenRCT2/OpenGraphics#6]
The root of this issue is that when we do the final trimming of images using ImageMagick, we tell IM to output the XY position of the trimmed image on the original canvas. This gives us the negative of the value we need to output to pos.txt. 

````
canvastex=$(convert "finished/pic$g.ppm" -trim -print '%X%Y' -quiet "finished/pic$g.ppm")
````

The problem occurs because of the way ImageMagick deals with trimming blank images, which occur relatively often with the peep sprites. IM generates what it calls a "missed image", a blank single pixel image, and outputs -1,-1 for the XY values. I originally assumed that there wasn't any situation where this XY value would be otherwise negative, so I did a very naive check for these missed images:

````
missed=${canvastex:0:1} # Catch missed (i.e. empty) images
if [ $missed == "-" ]; then
	posx=0
	posy=0
...
````

Peep sprites often wind up giving negative IM position values, so these are incorrectly interpreted as missed images and thus their actual position values are not recorded in pos.txt.

I'll have to detect missed images in a different way to solve this...

**Comment by Krutonium** [comment]
I'd suggest checking for the exact size of a missed image in the resulting file - I assume that's consistent, right?

**Comment by oli414** [comment]
Closing since we'll use a different rendering tool.
