### ISSUE TITLE
tutorial Simon Foster used to create tree assets

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenGraphics#9]
Simon Foster apparently spends the time to look at his youtube comments and post meaningful replies. I was reading a reply chain and found this link that he posted, which he said was the method used to create the trees RCT1 and RCT2:

http://www.animationartist.com/2000/Tutorials/LWTrees/lwtrees.html

**Comment by cobalthex** [comment]
here's a wayback link https://web.archive.org/web/20080320073733/http://www.animationartist.com/2000/Tutorials/LWTrees/lwtrees.html

**Comment by oli414** [comment]
Tutorial has been added to the wiki
